# NOTE: all are tagged with "ufw_rules" (see ufw/tasks/main.yml)
- name: UFW - Reset UFW rules (optional step)
  community.general.ufw:
    state: reset

- name: UFW - Set default policy to deny
  community.general.ufw:
    default: deny

- name: UFW - Allow SSH Server
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp

- name: UFW - Allow HTTP Server
  community.general.ufw:
    rule: allow
    port: 80
    proto: tcp

- name: UFW - Allow HTTPS Server
  community.general.ufw:
    rule: allow
    port: 443
    proto: tcp

- name: UFW - Enable UFW
  community.general.ufw:
    state: enabled
