---
- name: Tmux | Install tmux (Arch)
  community.general.pacman:
    name: tmux
    state: present
  become: true
  when: machine_os == 'archlinux'

- name: Tmux | Install tmux (Debian)
  ansible.builtin.apt:
    name: tmux
    state: present
  become: true
  when: machine_os == 'debian'

- name: Tmux | Install tmux (RedHat)
  ansible.builtin.dnf:
    name: tmux
    state: present
  become: true
  when: machine_os == 'redhat'

- name: Tmux | Link tmux.conf config
  ansible.builtin.file:
    src: "{{ ansible_facts['user_dir'] }}/dotfiles/tmux/.tmux.conf"
    dest: "{{ ansible_facts['user_dir'] }}/.tmux.conf"
    state: link

- name: Tmux | Link dotfiles/tmux configs to ~/.config/tmux
  ansible.builtin.file:
    src: "{{ ansible_facts['user_dir'] }}/dotfiles/tmux"
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux"
    state: link

- name: Tmux | Install tpm (git clone)
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_facts['user_dir'] }}/.config/tmux/plugins/tpm"
